In [1]:
import numpy as np

In [2]:
#Question 1
s
q1 = np.array([[1,2],[3,4]])
print(q1)

[[1 2]
 [3 4]]


In [3]:
#Question 2

q2 = np.random.random((3,4))
print(q2)

[[0.8289213  0.59156188 0.1519003  0.49478289]
 [0.76196095 0.85437616 0.91954266 0.67525148]
 [0.99940336 0.27706933 0.97652965 0.27041679]]


In [4]:
#Question 3

q31 = np.zeros((2,2))
q32 = np.ones((2,2))

print(q31,"\n\n",q32)

[[0. 0.]
 [0. 0.]] 

 [[1. 1.]
 [1. 1.]]


In [5]:
#Question 4

q4 = np.random.random((6,3)).T
print(q4)

[[0.39874074 0.98755802 0.40229903 0.99541262 0.88131248 0.13422314]
 [0.27069028 0.34666269 0.12250554 0.77279225 0.9113009  0.98441902]
 [0.52643157 0.86455739 0.32678314 0.73238042 0.36554061 0.43634893]]


In [6]:
#Question 5

n,p,m = 3,4,5

arr1 = np.random.random((n,p))
arr2 = np.random.random((p,m))

ans = np.dot(arr1,arr2)

print(arr1,"\n\n",arr2,"\n\n",ans)

[[0.99686898 0.17140874 0.87362946 0.27205692]
 [0.63077704 0.98212139 0.04403084 0.71197046]
 [0.6067255  0.559717   0.74232429 0.26122011]] 

 [[0.10377155 0.60263963 0.74982386 0.75298685 0.39622509]
 [0.1606027  0.88247384 0.2199211  0.25138852 0.57837803]
 [0.33190918 0.45542437 0.97573154 0.54451656 0.02985741]
 [0.24965403 0.1410878  0.70884838 0.9255692  0.50556784]] 

 [[0.48886109 1.18827253 1.83044748 1.52123264 0.6577511 ]
 [0.41554859 1.36733073 1.23660228 1.4048143  1.17923114]
 [0.4644518  1.23449998 1.48750551 1.2435479  0.71835625]]
